#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : trystatic
Version  : 1.0.0
Release  : 10
URL      : https://github.com/insilications/trystatic-clr/raw/master/dist/trystatic-1.0.0.tar.gz
Source0  : https://github.com/insilications/trystatic-clr/raw/master/dist/trystatic-1.0.0.tar.gz
Summary  : trystatic
Group    : Development/Tools
License  : MIT
Requires: trystatic-bin = %{version}-%{release}
Requires: trystatic-python = %{version}-%{release}
Requires: trystatic-python3 = %{version}-%{release}
Requires: fd
Requires: ripgrep
Requires: sd
BuildRequires : buildreq-distutils3
BuildRequires : setuptools-python

%description
==================================
        
        trystatic-clr

%package bin
Summary: bin components for the trystatic package.
Group: Binaries

%description bin
bin components for the trystatic package.


%package python
Summary: python components for the trystatic package.
Group: Default
Requires: trystatic-python3 = %{version}-%{release}

%description python
python components for the trystatic package.


%package python3
Summary: python3 components for the trystatic package.
Group: Default
Requires: python3-core

%description python3
python3 components for the trystatic package.


%prep
%setup -q -n trystatic-1.0.0
cd %{_builddir}/trystatic-1.0.0

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1617538813
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/trystatic

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
